# Generated by Django 4.2.2 on 2024-09-07 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0004_alter_payment_options_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="update",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
